Scrape wiki pages
mdn/short-descriptions pull request #11
Opened 2019-01-16 18:25 UTC by ddbeck

OK, this ought to ingest some wiki page summaries and resolve #9.

Running `npm run scrape <property>` fetches a page from the wiki, such as https://developer.mozilla.org/docs/Web/CSS/animation-delay?raw&summary:

```html
The <strong><code>animation-delay</code></strong> <a href="/en-US/docs/CSS">CSS</a> property sets when an animation starts. The animation can start later, immediately from its beginning, or immediately and partway through the animation.
```

And writes out this:

```json
{
  "css": {
    "properties": {
      "animation-delay": {
        "__short_description": "The <strong><code>animation-delay</code></strong> <a href='https://developer.mozilla.org/docs/CSS'>CSS</a> property sets when an animation starts. The animation can start later, immediately from its beginning, or immediately and partway through the animation."
      }
    }
  }
}
```

A few additional notes:

* I changed the Airbnb eslint rules to be less annoying to our particular use. When time permits, I'll see about setting up Travis CI to run eslint on PRs.
* I've been staring at this a bit too long. I expect there are obvious bugs.

I'd welcome any and all comments. Thank you, @wbamberg!

2019-01-17 18:46 UTC, octref commented
Wow, this is incredible.

Is `?raw&summary` a public URL that I can use? I'm trying to add svg data from MDN and SVG2 spec, and I was using the `$json` API. This would have been much better!

2019-01-17 19:46 UTC, ddbeck commented
@octref I'm pretty sure it's intended for public consumption. It's a bit hard to find, but parameters for pages are documented [on this page](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/Document_parameters#URL_parameters) (searching MDN for "URL parameters" returns _a lot_ of results, believe it or not 😆)

2019-01-24 02:18 UTC, wbamberg reviewed
The code generally looks sensible.

When I run `npm run scrape margin` I get:

```
> mdn-short-descriptions@0.0.1 scrape /Users/Mozilla/git/people/ddbeck/short-descriptions
> node scripts/scrape.js "margin"

Trace: { Error: EEXIST: file already exists, mkdir '/Users/Mozilla/git/people/ddbeck/short-descriptions/descriptions/css/properties'
    at Object.fs.mkdirSync (fs.js:885:18)
    at writeToFile (/Users/Mozilla/git/people/ddbeck/short-descriptions/scripts/scrape.js:97:6)
    at delay.then.then.then.then.then.then.then.html (/Users/Mozilla/git/people/ddbeck/short-descriptions/scripts/scrape.js:119:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/Users/Mozilla/git/people/ddbeck/short-descriptions/descriptions/css/properties' }
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

2019-01-24 02:18 UTC, wbamberg commented on scripts/scrape.js
> +  a.href = a.href;
:)

2019-01-24 02:18 UTC, wbamberg commented on scripts/scrape.js
> +    a.href = a.href.replace(/[/]\w\w-\w\w(?=[/])/g, '');
FWIW I'm not sure about this regex. As I read it will match any section of the path containing 2 x 2-character strings separated by "-". So it will match "en-US" but also non-locales like "ff-ff" but not actual locales like "fr". Also it will match multiple values, so:

`https://developer.mozilla.org/en-US/docs/Web/API/la-la/`

becomes 

`https://developer.mozilla.org/docs/Web/API/`

I think the true logic of "delocalize" is: if the first path section isn't "docs", remove it. Also I wouldn't use a regex for this because I don't think they are readable, but that's really just a preference.

2019-01-24 13:28 UTC, ddbeck commented on scripts/scrape.js
> +    a.href = a.href.replace(/[/]\w\w-\w\w(?=[/])/g, '');
No, that's a good point. I had in my head that I was trying to subdue a string, rather than a URL that's got some actual rules to it. I'll re-do this with Node's `URL` module.

2019-01-24 13:40 UTC, ddbeck commented on scripts/scrape.js
> +  fs.writeFile(dest, `${JSON.stringify(data, null, 2)}\n`, (err) => { if (err) throw err; });
This is a weird mix of synchronous and asynchronous `fs` calls (one of which with a meaningless error handler), which may be contributing to the error @wbamberg spotted. Going to mess with this a bit.

2019-01-24 14:09 UTC, ddbeck commented on scripts/scrape.js
> +    a.href = a.href.replace(/[/]\w\w-\w\w(?=[/])/g, '');
Turned out to be simpler than that, even. Fixed!

2019-01-24 14:34 UTC, ddbeck commented
@wbamberg Would you mind running the script again to see if you still get that error? I wasn't able to reproduce it myself. It seems like `EEXIST` should never happen on `mkdirSync` (at least when `{ recursive: true }`) but I was also calling it wrong, so who knows.

2019-01-24 18:25 UTC, wbamberg commented
From what I can tell, `mkdirSync` will throw if the given directory exists, and that's what I'm seeing. What works is if I change the code like:

```
  const dir = path.dirname(dest);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(dest, `${JSON.stringify(data, null, 2)}\n`);
```

But I wonder why you can't reproduce it. (from my reading `recursive` is different, it means I can give it `multiple/level/path` and have `multiple` and `level` created for me if they don't exist).

2019-01-24 18:59 UTC, wbamberg requested changes
With the change in https://github.com/mdn/short-descriptions/pull/11#issuecomment-457304038 this seems to work just great. I tried running it with a few named properties, and then with no arguments, to fetch short descriptions for all CSS properties. With no arguments it had one failure, a transient 504 fetching `background-image`, and otherwise worked perfectly as far as I could see.

Since of course there are already some (artisanally crafted) short descriptions in this repo, it generated some slightly interesting diffs for me:

```
diff --git a/descriptions/css/properties/animation-fill-mode.json b/descriptions/css/properties/animation-fill-mode.json
index a9a4f51..9610277 100644
--- a/descriptions/css/properties/animation-fill-mode.json
+++ b/descriptions/css/properties/animation-fill-mode.json
@@ -2,7 +2,7 @@
   "css": {
     "properties": {
       "animation-fill-mode": {
-        "__short_description": "The <strong><code>animation-fill-mode</code></strong> <a href='https://developer.mozilla.org/en/CSS'>CSS</a> property sets how a CSS animation applies styles to its target before and after its execution."
+        "__short_description": "The <strong><code>animation-fill-mode</code></strong> <a href='https://developer.mozilla.org/CSS'>CSS</a> property sets how a CSS animation applies styles to its target before and after its execution."
       }
     }
   }
diff --git a/descriptions/css/properties/animation-iteration-count.json b/descriptions/css/properties/animation-iteration-count.json
index 5e48e50..1b88292 100644
--- a/descriptions/css/properties/animation-iteration-count.json
+++ b/descriptions/css/properties/animation-iteration-count.json
@@ -2,7 +2,7 @@
   "css": {
     "properties": {
       "animation-iteration-count": {
-        "__short_description": "The <strong><code>animation-iteration-count</code></strong> <a href='https://developer.mozilla.org/en/CSS'>CSS</a> property sets the number of times an animation cycle should be played before stopping."
+        "__short_description": "The <strong><code>animation-iteration-count</code></strong> <a href='https://developer.mozilla.org/CSS'>CSS</a> property sets the number of times an animation cycle should be played before stopping."
       }
     }
   }
diff --git a/descriptions/css/properties/background-image.json b/descriptions/css/properties/background-image.json
index 776975a..7fa71b8 100644
--- a/descriptions/css/properties/background-image.json
+++ b/descriptions/css/properties/background-image.json
@@ -2,7 +2,7 @@
   "css": {
     "properties": {
       "background-image": {
-        "__short_description": "The <strong><code>background-image</code></strong> <a href='https://developer.mozilla.org/docs/CSS'>CSS</a> property sets one or more background images on an element."
+        "__short_description": "The <strong><code>background-image</code></strong> <a href='https://developer.mozilla.org/docs/Web/CSS'>CSS</a> property sets one or more background images on an element."
       }
     }
   }
diff --git a/descriptions/css/properties/opacity.json b/descriptions/css/properties/opacity.json
index 38f1db6..abb28ac 100644
--- a/descriptions/css/properties/opacity.json
+++ b/descriptions/css/properties/opacity.json
@@ -2,7 +2,7 @@
   "css": {
     "properties": {
       "opacity": {
-        "__short_description": "The <strong><code>opacity</code></strong> CSS property sets the transparency of an element or the degree to which content behind an element is visible."
+        "__short_description": "The <strong><code>opacity</code></strong> CSS property sets the opacity of an element. Opacity is the degree to which content behind an element is hidden, and is the opposite of transparency."
       }
     }
   }
diff --git a/descriptions/css/properties/padding-right.json b/descriptions/css/properties/padding-right.json
index d6c53af..8645262 100644
--- a/descriptions/css/properties/padding-right.json
+++ b/descriptions/css/properties/padding-right.json
@@ -2,7 +2,7 @@
   "css": {
     "properties": {
       "padding-right": {
-        "__short_description": "The<strong> <code>padding-right</code> </strong><a href='https://developer.mozilla.org/en/CSS'>CSS</a> property sets the width of the <a href='https://developer.mozilla.org/en/CSS/box_model#padding-area'>padding area</a> on the right side of an element."
+        "__short_description": "The<strong> <code>padding-right</code> </strong><a href='https://developer.mozilla.org/CSS'>CSS</a> property sets the width of the <a href='https://developer.mozilla.org/CSS/box_model#padding-area'>padding area</a> on the right side of an element."
       }
     }
   }
```

These are mostly but not entirely because of the URL normalizing it's doing.

So this is great: in terms of workflow we could run this, and get a diff, and if the diff is legitimate (i.e. if the Wiki updates that it reflects are OK) we can make that into a PR against the short-descriptions repo to update the descriptions. Awesome work @ddbeck !

I'm also wondering now how we would be able to use tools like this to migrate Wiki content into a structured form....

One thing: I think it would be helpful to emit a summary of what the command did. When I ran `npm run scrape`, as I said, there was a single failure, the 504 getting `background-image`. What I see in the output is a massive traceback for that, and no other output for the command. It's hard to see the name of the property that failed in the massive traceback, and there's no indication of what actually succeeded.

So it would be great to have something like:

```
Successfully scraped 350 properties
Failed to scrape: background-image
```

...printed at the end. Or something like that. What do you think?

2019-01-24 19:00 UTC, wbamberg commented on scripts/scrape.js
> +    a.href = a.href.replace(/[/]\w\w-\w\w(?=[/])/g, '');
Yeah, the fixed version is more verbose but easier to read and more accurate 👍

2019-01-24 19:57 UTC, ddbeck commented
@wbamberg Thanks for the fix for `mkdirSync`! I'm still really curious why it seems to be a machine-specific thing (maybe differences in underlying syscalls?), but if we've got a fix, then I guess it doesn't actually matter.

> So this is great: in terms of workflow we could run this, and get a diff, and if the diff is legitimate (i.e. if the Wiki updates that it reflects are OK) we can make that into a PR against the short-descriptions repo to update the descriptions.

Yeah, I thought the diffs were pretty tractable too (plus `--word-diff` will highlight intra-line, like a GitHub PR does).

About a summary and the massive traceback: yeah, I should fix those both. There's two places where I ought to catch some likely errors: fetching the property URL and writing to disk (obviously).

I'll work on these changes soon! Thanks again for your feedback, Will!

2019-01-24 21:38 UTC, wbamberg commented
Thanks Daniel!

> About a summary and the massive traceback: yeah, I should fix those both. 

Just to be clear: I didn't mind the long traceback, I was more concerned about having a summary.

2019-01-28 20:38 UTC, ddbeck commented
Thanks again for the feedback, Will. Here's a summary of what's changed:

* There's now a summary when you run the scraper. It looks like this:

   ```
   $ npm run scrape -- margin background overflow-block fake-property teapot

   > mdn-short-descriptions@0.0.1 scrape /Users/ddbeck/TheWork/Mozilla/short-descriptions/ddbeck-short-descriptions
   > node scripts/scrape.js "margin" "background" "overflow-block" "fake-property" "teapot"

   Trace: <imagine long traceback here>

   Attempted to scrape 5 properties.
   Successfully scraped 2 properties.
   Failed to scrape 3 properties:
     overflow-block: No `mdn_url` found
     fake-property: Property not found
     teapot: StatusCodeError: 418 - {"type":"Buffer","data":[52,49,56,32,73,39,109,32,97,32,116,101,97,112,111,116]}
   ```
* The script checks for the existence of the destination directory. Hopefully no more errors from that.
* While writing the summary, I found the original `.then` chain to be confusing and pointless because most of it is synchronous anyway. I rewrote that to be (hopefully) more tidy with async/await. It might help to look at that commit in isolation, to see the changes.

Let me know what you think. Thanks again!

2019-02-05 05:41 UTC, wbamberg approved these changes
This seems to work great, and I like the changes you've made to the `main` function. Very nice work Daniel :).

2019-02-05 05:41 UTC, merged